<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>source.sciter.selectors</string>
    <key>name</key>
    <string>Sciter CSS Selectors</string>
    <key>fileTypes</key>
    <array/>
    <key>uuid</key>
    <string>cccd98df-a526-4251-82a2-3908400ca427</string>
    <key>hideFromUser</key>
    <true/>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#selector</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>selector</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#attribute-selector</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#class-selector</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#id-selector</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#simple-pseudo-class-selector</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#after-before</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#not-selector</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#child-selector</string>
          </dict>
        </array>
      </dict>
      <key>attribute-selector</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>end</key>
        <string>\]</string>
        <key>name</key>
        <string>entity.name.selector</string>
      </dict>
      <key>class-selector</key>
      <dict>
        <key>match</key>
        <string>\.[\w-]+</string>
        <key>name</key>
        <string>entity.name.selector</string>
      </dict>
      <key>id-selector</key>
      <dict>
        <key>match</key>
        <string>\#[\w-]+</string>
        <key>name</key>
        <string>entity.name.selector</string>
      </dict>
      <key>simple-pseudo-class-selector</key>
      <dict>
        <key>match</key>
        <string>(:)(first-child|last-child|link|visited|active|hover|focus|tab-focus|focusable|current|checked|disabled|read-only|expanded|collapsed|incomplete|busy|empty|has-children(-of-type)?|has-child(-of-type)?|animating|popup|owns-popup|synthetic|drop-target|drag-over|moving|copying|drag-source|rtl|ltr|invalid|drop-marker|content-editable|node|root)</string>
        <key>name</key>
        <string>entity.name.selector</string>
      </dict>
      <key>after-before</key>
      <dict>
        <key>match</key>
        <string>(::)(after|before)</string>
        <key>name</key>
        <string>entity.name.selector</string>
      </dict>
      <key>not-selector</key>
      <dict>
        <key>begin</key>
        <string>\s*(:not)\s*(\()\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.c</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.function.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(\))\s*</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.function.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#selector</string>
          </dict>
        </array>
      </dict>
      <key>child-selector</key>
      <dict>
        <key>begin</key>
        <string>\s*(:(?:nth-child|nth-last-child|only-child|only-of-type|has-child-of-type|has-children-of-type))\s*(\()\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.c</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.function.css</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\s*(\))\s*</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.function.css</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#selector</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>